/*
 * Copyright (c) 2002-2008 LWJGL Project
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * * Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the distribution.
 *
 * * Neither the name of 'LWJGL' nor the names of
 *   its contributors may be used to endorse or promote products derived
 *   from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.lwjgl.opengl;

public class ContextCapabilities {

    public final boolean GL_AMD_blend_minmax_factor;
    public final boolean GL_AMD_conservative_depth;
    public final boolean GL_AMD_debug_output;
    public final boolean GL_AMD_depth_clamp_separate;
    public final boolean GL_AMD_draw_buffers_blend;
    public final boolean GL_AMD_interleaved_elements;
    public final boolean GL_AMD_multi_draw_indirect;
    public final boolean GL_AMD_name_gen_delete;
    public final boolean GL_AMD_performance_monitor;
    public final boolean GL_AMD_pinned_memory;
    public final boolean GL_AMD_query_buffer_object;
    public final boolean GL_AMD_sample_positions;
    public final boolean GL_AMD_seamless_cubemap_per_texture;
    public final boolean GL_AMD_shader_atomic_counter_ops;
    public final boolean GL_AMD_shader_stencil_export;
    public final boolean GL_AMD_shader_trinary_minmax;
    public final boolean GL_AMD_sparse_texture;
    public final boolean GL_AMD_stencil_operation_extended;
    public final boolean GL_AMD_texture_texture4;
    public final boolean GL_AMD_transform_feedback3_lines_triangles;
    public final boolean GL_AMD_vertex_shader_layer;
    public final boolean GL_AMD_vertex_shader_tessellator;
    public final boolean GL_AMD_vertex_shader_viewport_index;
    public final boolean GL_APPLE_aux_depth_stencil;
    public final boolean GL_APPLE_client_storage;
    public final boolean GL_APPLE_element_array;
    public final boolean GL_APPLE_fence;
    public final boolean GL_APPLE_float_pixels;
    public final boolean GL_APPLE_flush_buffer_range;
    public final boolean GL_APPLE_object_purgeable;
    public final boolean GL_APPLE_packed_pixels;
    public final boolean GL_APPLE_rgb_422;
    public final boolean GL_APPLE_row_bytes;
    public final boolean GL_APPLE_texture_range;
    public final boolean GL_APPLE_vertex_array_object;
    public final boolean GL_APPLE_vertex_array_range;
    public final boolean GL_APPLE_vertex_program_evaluators;
    public final boolean GL_APPLE_ycbcr_422;
    public final boolean GL_ARB_ES2_compatibility;
    public final boolean GL_ARB_ES3_1_compatibility;
    public final boolean GL_ARB_ES3_compatibility;
    public final boolean GL_ARB_arrays_of_arrays;
    public final boolean GL_ARB_base_instance;
    public final boolean GL_ARB_bindless_texture;
    public final boolean GL_ARB_blend_func_extended;
    public final boolean GL_ARB_buffer_storage;
    public final boolean GL_ARB_cl_event;
    public final boolean GL_ARB_clear_buffer_object;
    public final boolean GL_ARB_clear_texture;
    public final boolean GL_ARB_clip_control;
    public final boolean GL_ARB_color_buffer_float;
    public final boolean GL_ARB_compatibility;
    public final boolean GL_ARB_compressed_texture_pixel_storage;
    public final boolean GL_ARB_compute_shader;
    public final boolean GL_ARB_compute_variable_group_size;
    public final boolean GL_ARB_conditional_render_inverted;
    public final boolean GL_ARB_conservative_depth;
    public final boolean GL_ARB_copy_buffer;
    public final boolean GL_ARB_copy_image;
    public final boolean GL_ARB_cull_distance;
    public final boolean GL_ARB_debug_output;
    public final boolean GL_ARB_depth_buffer_float;
    public final boolean GL_ARB_depth_clamp;
    public final boolean GL_ARB_depth_texture;
    public final boolean GL_ARB_derivative_control;
    public final boolean GL_ARB_direct_state_access;
    public final boolean GL_ARB_draw_buffers;
    public final boolean GL_ARB_draw_buffers_blend;
    public final boolean GL_ARB_draw_elements_base_vertex;
    public final boolean GL_ARB_draw_indirect;
    public final boolean GL_ARB_draw_instanced;
    public final boolean GL_ARB_enhanced_layouts;
    public final boolean GL_ARB_explicit_attrib_location;
    public final boolean GL_ARB_explicit_uniform_location;
    public final boolean GL_ARB_fragment_coord_conventions;
    public final boolean GL_ARB_fragment_layer_viewport;
    public final boolean GL_ARB_fragment_program;
    public final boolean GL_ARB_fragment_program_shadow;
    public final boolean GL_ARB_fragment_shader;
    public final boolean GL_ARB_framebuffer_no_attachments;
    public final boolean GL_ARB_framebuffer_object;
    public final boolean GL_ARB_framebuffer_sRGB;
    public final boolean GL_ARB_geometry_shader4;
    public final boolean GL_ARB_get_program_binary;
    public final boolean GL_ARB_get_texture_sub_image;
    public final boolean GL_ARB_gpu_shader5;
    public final boolean GL_ARB_gpu_shader_fp64;
    public final boolean GL_ARB_half_float_pixel;
    public final boolean GL_ARB_half_float_vertex;
    public final boolean GL_ARB_imaging;
    public final boolean GL_ARB_indirect_parameters;
    public final boolean GL_ARB_instanced_arrays;
    public final boolean GL_ARB_internalformat_query;
    public final boolean GL_ARB_internalformat_query2;
    public final boolean GL_ARB_invalidate_subdata;
    public final boolean GL_ARB_map_buffer_alignment;
    public final boolean GL_ARB_map_buffer_range;
    public final boolean GL_ARB_matrix_palette;
    public final boolean GL_ARB_multi_bind;
    public final boolean GL_ARB_multi_draw_indirect;
    public final boolean GL_ARB_multisample;
    public final boolean GL_ARB_multitexture;
    public final boolean GL_ARB_occlusion_query;
    public final boolean GL_ARB_occlusion_query2;
    public final boolean GL_ARB_pipeline_statistics_query;
    public final boolean GL_ARB_pixel_buffer_object;
    public final boolean GL_ARB_point_parameters;
    public final boolean GL_ARB_point_sprite;
    public final boolean GL_ARB_program_interface_query;
    public final boolean GL_ARB_provoking_vertex;
    public final boolean GL_ARB_query_buffer_object;
    public final boolean GL_ARB_robust_buffer_access_behavior;
    public final boolean GL_ARB_robustness;
    public final boolean GL_ARB_robustness_isolation;
    public final boolean GL_ARB_sample_shading;
    public final boolean GL_ARB_sampler_objects;
    public final boolean GL_ARB_seamless_cube_map;
    public final boolean GL_ARB_seamless_cubemap_per_texture;
    public final boolean GL_ARB_separate_shader_objects;
    public final boolean GL_ARB_shader_atomic_counters;
    public final boolean GL_ARB_shader_bit_encoding;
    public final boolean GL_ARB_shader_draw_parameters;
    public final boolean GL_ARB_shader_group_vote;
    public final boolean GL_ARB_shader_image_load_store;
    public final boolean GL_ARB_shader_image_size;
    public final boolean GL_ARB_shader_objects;
    public final boolean GL_ARB_shader_precision;
    public final boolean GL_ARB_shader_stencil_export;
    public final boolean GL_ARB_shader_storage_buffer_object;
    public final boolean GL_ARB_shader_subroutine;
    public final boolean GL_ARB_shader_texture_image_samples;
    public final boolean GL_ARB_shader_texture_lod;
    public final boolean GL_ARB_shading_language_100;
    public final boolean GL_ARB_shading_language_420pack;
    public final boolean GL_ARB_shading_language_include;
    public final boolean GL_ARB_shading_language_packing;
    public final boolean GL_ARB_shadow;
    public final boolean GL_ARB_shadow_ambient;
    public final boolean GL_ARB_sparse_buffer;
    public final boolean GL_ARB_sparse_texture;
    public final boolean GL_ARB_stencil_texturing;
    public final boolean GL_ARB_sync;
    public final boolean GL_ARB_tessellation_shader;
    public final boolean GL_ARB_texture_barrier;
    public final boolean GL_ARB_texture_border_clamp;
    public final boolean GL_ARB_texture_buffer_object;
    public final boolean GL_ARB_texture_buffer_object_rgb32;
    public final boolean GL_ARB_texture_buffer_range;
    public final boolean GL_ARB_texture_compression;
    public final boolean GL_ARB_texture_compression_bptc;
    public final boolean GL_ARB_texture_compression_rgtc;
    public final boolean GL_ARB_texture_cube_map;
    public final boolean GL_ARB_texture_cube_map_array;
    public final boolean GL_ARB_texture_env_add;
    public final boolean GL_ARB_texture_env_combine;
    public final boolean GL_ARB_texture_env_crossbar;
    public final boolean GL_ARB_texture_env_dot3;
    public final boolean GL_ARB_texture_float;
    public final boolean GL_ARB_texture_gather;
    public final boolean GL_ARB_texture_mirror_clamp_to_edge;
    public final boolean GL_ARB_texture_mirrored_repeat;
    public final boolean GL_ARB_texture_multisample;
    public final boolean GL_ARB_texture_non_power_of_two;
    public final boolean GL_ARB_texture_query_levels;
    public final boolean GL_ARB_texture_query_lod;
    public final boolean GL_ARB_texture_rectangle;
    public final boolean GL_ARB_texture_rg;
    public final boolean GL_ARB_texture_rgb10_a2ui;
    public final boolean GL_ARB_texture_stencil8;
    public final boolean GL_ARB_texture_storage;
    public final boolean GL_ARB_texture_storage_multisample;
    public final boolean GL_ARB_texture_swizzle;
    public final boolean GL_ARB_texture_view;
    public final boolean GL_ARB_timer_query;
    public final boolean GL_ARB_transform_feedback2;
    public final boolean GL_ARB_transform_feedback3;
    public final boolean GL_ARB_transform_feedback_instanced;
    public final boolean GL_ARB_transform_feedback_overflow_query;
    public final boolean GL_ARB_transpose_matrix;
    public final boolean GL_ARB_uniform_buffer_object;
    public final boolean GL_ARB_vertex_array_bgra;
    public final boolean GL_ARB_vertex_array_object;
    public final boolean GL_ARB_vertex_attrib_64bit;
    public final boolean GL_ARB_vertex_attrib_binding;
    public final boolean GL_ARB_vertex_blend;
    public final boolean GL_ARB_vertex_buffer_object;
    public final boolean GL_ARB_vertex_program;
    public final boolean GL_ARB_vertex_shader;
    public final boolean GL_ARB_vertex_type_10f_11f_11f_rev;
    public final boolean GL_ARB_vertex_type_2_10_10_10_rev;
    public final boolean GL_ARB_viewport_array;
    public final boolean GL_ARB_window_pos;
    public final boolean GL_ATI_draw_buffers;
    public final boolean GL_ATI_element_array;
    public final boolean GL_ATI_envmap_bumpmap;
    public final boolean GL_ATI_fragment_shader;
    public final boolean GL_ATI_map_object_buffer;
    public final boolean GL_ATI_meminfo;
    public final boolean GL_ATI_pn_triangles;
    public final boolean GL_ATI_separate_stencil;
    public final boolean GL_ATI_shader_texture_lod;
    public final boolean GL_ATI_text_fragment_shader;
    public final boolean GL_ATI_texture_compression_3dc;
    public final boolean GL_ATI_texture_env_combine3;
    public final boolean GL_ATI_texture_float;
    public final boolean GL_ATI_texture_mirror_once;
    public final boolean GL_ATI_vertex_array_object;
    public final boolean GL_ATI_vertex_attrib_array_object;
    public final boolean GL_ATI_vertex_streams;
    public final boolean GL_EXT_Cg_shader;
    public final boolean GL_EXT_abgr;
    public final boolean GL_EXT_bgra;
    public final boolean GL_EXT_bindable_uniform;
    public final boolean GL_EXT_blend_color;
    public final boolean GL_EXT_blend_equation_separate;
    public final boolean GL_EXT_blend_func_separate;
    public final boolean GL_EXT_blend_minmax;
    public final boolean GL_EXT_blend_subtract;
    public final boolean GL_EXT_compiled_vertex_array;
    public final boolean GL_EXT_depth_bounds_test;
    public final boolean GL_EXT_direct_state_access;
    public final boolean GL_EXT_draw_buffers2;
    public final boolean GL_EXT_draw_instanced;
    public final boolean GL_EXT_draw_range_elements;
    public final boolean GL_EXT_fog_coord;
    public final boolean GL_EXT_framebuffer_blit;
    public final boolean GL_EXT_framebuffer_multisample;
    public final boolean GL_EXT_framebuffer_multisample_blit_scaled;
    public final boolean GL_EXT_framebuffer_object;
    public final boolean GL_EXT_framebuffer_sRGB;
    public final boolean GL_EXT_geometry_shader4;
    public final boolean GL_EXT_gpu_program_parameters;
    public final boolean GL_EXT_gpu_shader4;
    public final boolean GL_EXT_multi_draw_arrays;
    public final boolean GL_EXT_packed_depth_stencil;
    public final boolean GL_EXT_packed_float;
    public final boolean GL_EXT_packed_pixels;
    public final boolean GL_EXT_paletted_texture;
    public final boolean GL_EXT_pixel_buffer_object;
    public final boolean GL_EXT_point_parameters;
    public final boolean GL_EXT_provoking_vertex;
    public final boolean GL_EXT_rescale_normal;
    public final boolean GL_EXT_secondary_color;
    public final boolean GL_EXT_separate_shader_objects;
    public final boolean GL_EXT_separate_specular_color;
    public final boolean GL_EXT_shader_image_load_store;
    public final boolean GL_EXT_shadow_funcs;
    public final boolean GL_EXT_shared_texture_palette;
    public final boolean GL_EXT_stencil_clear_tag;
    public final boolean GL_EXT_stencil_two_side;
    public final boolean GL_EXT_stencil_wrap;
    public final boolean GL_EXT_texture_3d;
    public final boolean GL_EXT_texture_array;
    public final boolean GL_EXT_texture_buffer_object;
    public final boolean GL_EXT_texture_compression_latc;
    public final boolean GL_EXT_texture_compression_rgtc;
    public final boolean GL_EXT_texture_compression_s3tc;
    public final boolean GL_EXT_texture_env_combine;
    public final boolean GL_EXT_texture_env_dot3;
    public final boolean GL_EXT_texture_filter_anisotropic;
    public final boolean GL_EXT_texture_integer;
    public final boolean GL_EXT_texture_lod_bias;
    public final boolean GL_EXT_texture_mirror_clamp;
    public final boolean GL_EXT_texture_rectangle;
    public final boolean GL_EXT_texture_sRGB;
    public final boolean GL_EXT_texture_sRGB_decode;
    public final boolean GL_EXT_texture_shared_exponent;
    public final boolean GL_EXT_texture_snorm;
    public final boolean GL_EXT_texture_swizzle;
    public final boolean GL_EXT_timer_query;
    public final boolean GL_EXT_transform_feedback;
    public final boolean GL_EXT_vertex_array_bgra;
    public final boolean GL_EXT_vertex_attrib_64bit;
    public final boolean GL_EXT_vertex_shader;
    public final boolean GL_EXT_vertex_weighting;
    public final boolean OpenGL11;
    public final boolean OpenGL12;
    public final boolean OpenGL13;
    public final boolean OpenGL14;
    public final boolean OpenGL15;
    public final boolean OpenGL20;
    public final boolean OpenGL21;
    public final boolean OpenGL30;
    public final boolean OpenGL31;
    public final boolean OpenGL32;
    public final boolean OpenGL33;
    public final boolean OpenGL40;
    public final boolean OpenGL41;
    public final boolean OpenGL42;
    public final boolean OpenGL43;
    public final boolean OpenGL44;
    public final boolean OpenGL45;
    public final boolean GL_GREMEDY_frame_terminator;
    public final boolean GL_GREMEDY_string_marker;
    public final boolean GL_HP_occlusion_test;
    public final boolean GL_IBM_rasterpos_clip;
    public final boolean GL_INTEL_map_texture;
    public final boolean GL_KHR_context_flush_control;
    public final boolean GL_KHR_debug;
    public final boolean GL_KHR_robust_buffer_access_behavior;
    public final boolean GL_KHR_robustness;
    public final boolean GL_KHR_texture_compression_astc_ldr;
    public final boolean GL_NVX_gpu_memory_info;
    public final boolean GL_NV_bindless_multi_draw_indirect;
    public final boolean GL_NV_bindless_texture;
    public final boolean GL_NV_blend_equation_advanced;
    public final boolean GL_NV_blend_square;
    public final boolean GL_NV_compute_program5;
    public final boolean GL_NV_conditional_render;
    public final boolean GL_NV_copy_depth_to_color;
    public final boolean GL_NV_copy_image;
    public final boolean GL_NV_deep_texture3D;
    public final boolean GL_NV_depth_buffer_float;
    public final boolean GL_NV_depth_clamp;
    public final boolean GL_NV_draw_texture;
    public final boolean GL_NV_evaluators;
    public final boolean GL_NV_explicit_multisample;
    public final boolean GL_NV_fence;
    public final boolean GL_NV_float_buffer;
    public final boolean GL_NV_fog_distance;
    public final boolean GL_NV_fragment_program;
    public final boolean GL_NV_fragment_program2;
    public final boolean GL_NV_fragment_program4;
    public final boolean GL_NV_fragment_program_option;
    public final boolean GL_NV_framebuffer_multisample_coverage;
    public final boolean GL_NV_geometry_program4;
    public final boolean GL_NV_geometry_shader4;
    public final boolean GL_NV_gpu_program4;
    public final boolean GL_NV_gpu_program5;
    public final boolean GL_NV_gpu_program5_mem_extended;
    public final boolean GL_NV_gpu_shader5;
    public final boolean GL_NV_half_float;
    public final boolean GL_NV_light_max_exponent;
    public final boolean GL_NV_multisample_coverage;
    public final boolean GL_NV_multisample_filter_hint;
    public final boolean GL_NV_occlusion_query;
    public final boolean GL_NV_packed_depth_stencil;
    public final boolean GL_NV_parameter_buffer_object;
    public final boolean GL_NV_parameter_buffer_object2;
    public final boolean GL_NV_path_rendering;
    public final boolean GL_NV_pixel_data_range;
    public final boolean GL_NV_point_sprite;
    public final boolean GL_NV_present_video;
    public final boolean GL_NV_primitive_restart;
    public final boolean GL_NV_register_combiners;
    public final boolean GL_NV_register_combiners2;
    public final boolean GL_NV_shader_atomic_counters;
    public final boolean GL_NV_shader_atomic_float;
    public final boolean GL_NV_shader_buffer_load;
    public final boolean GL_NV_shader_buffer_store;
    public final boolean GL_NV_shader_storage_buffer_object;
    public final boolean GL_NV_tessellation_program5;
    public final boolean GL_NV_texgen_reflection;
    public final boolean GL_NV_texture_barrier;
    public final boolean GL_NV_texture_compression_vtc;
    public final boolean GL_NV_texture_env_combine4;
    public final boolean GL_NV_texture_expand_normal;
    public final boolean GL_NV_texture_multisample;
    public final boolean GL_NV_texture_rectangle;
    public final boolean GL_NV_texture_shader;
    public final boolean GL_NV_texture_shader2;
    public final boolean GL_NV_texture_shader3;
    public final boolean GL_NV_transform_feedback;
    public final boolean GL_NV_transform_feedback2;
    public final boolean GL_NV_vertex_array_range;
    public final boolean GL_NV_vertex_array_range2;
    public final boolean GL_NV_vertex_attrib_integer_64bit;
    public final boolean GL_NV_vertex_buffer_unified_memory;
    public final boolean GL_NV_vertex_program;
    public final boolean GL_NV_vertex_program1_1;
    public final boolean GL_NV_vertex_program2;
    public final boolean GL_NV_vertex_program2_option;
    public final boolean GL_NV_vertex_program3;
    public final boolean GL_NV_vertex_program4;
    public final boolean GL_NV_video_capture;
    public final boolean GL_SGIS_generate_mipmap;
    public final boolean GL_SGIS_texture_lod;
    public final boolean GL_SUN_slice_accum;

    ContextCapabilities() {
        GLCapabilities caps = GL.getCapabilities();
        GL_AMD_blend_minmax_factor = caps.GL_AMD_blend_minmax_factor;
        GL_AMD_conservative_depth = caps.GL_AMD_conservative_depth;
        GL_AMD_debug_output = caps.GL_AMD_debug_output;
        GL_AMD_depth_clamp_separate = caps.GL_AMD_depth_clamp_separate;
        GL_AMD_draw_buffers_blend = caps.GL_AMD_draw_buffers_blend;
        GL_AMD_interleaved_elements = caps.GL_AMD_interleaved_elements;
        GL_AMD_multi_draw_indirect = false;
        GL_AMD_name_gen_delete = false;
        GL_AMD_performance_monitor = caps.GL_AMD_performance_monitor;
        GL_AMD_pinned_memory = caps.GL_AMD_pinned_memory;
        GL_AMD_query_buffer_object = caps.GL_AMD_query_buffer_object;
        GL_AMD_sample_positions = caps.GL_AMD_sample_positions;
        GL_AMD_seamless_cubemap_per_texture = caps.GL_AMD_seamless_cubemap_per_texture;
        GL_AMD_shader_atomic_counter_ops = caps.GL_AMD_shader_atomic_counter_ops;
        GL_AMD_shader_stencil_export = caps.GL_AMD_shader_stencil_export;
        GL_AMD_shader_trinary_minmax = caps.GL_AMD_shader_trinary_minmax;
        GL_AMD_sparse_texture = caps.GL_AMD_sparse_texture;
        GL_AMD_stencil_operation_extended = caps.GL_AMD_stencil_operation_extended;
        GL_AMD_texture_texture4 = caps.GL_AMD_texture_texture4;
        GL_AMD_transform_feedback3_lines_triangles = caps.GL_AMD_transform_feedback3_lines_triangles;
        GL_AMD_vertex_shader_layer = caps.GL_AMD_vertex_shader_layer;
        GL_AMD_vertex_shader_tessellator = caps.GL_AMD_vertex_shader_tessellator;
        GL_AMD_vertex_shader_viewport_index = caps.GL_AMD_vertex_shader_viewport_index;
        GL_APPLE_aux_depth_stencil = false;
        GL_APPLE_client_storage = false;
        GL_APPLE_element_array = false;
        GL_APPLE_fence = false;
        GL_APPLE_float_pixels = false;
        GL_APPLE_flush_buffer_range = false;
        GL_APPLE_object_purgeable = false;
        GL_APPLE_packed_pixels = false;
        GL_APPLE_rgb_422 = false;
        GL_APPLE_row_bytes = false;
        GL_APPLE_texture_range = false;
        GL_APPLE_vertex_array_object = false;
        GL_APPLE_vertex_array_range = false;
        GL_APPLE_vertex_program_evaluators = false;
        GL_APPLE_ycbcr_422 = false;
        GL_ARB_ES2_compatibility = caps.GL_ARB_ES2_compatibility;
        GL_ARB_ES3_1_compatibility = caps.GL_ARB_ES3_1_compatibility;
        GL_ARB_ES3_compatibility = caps.GL_ARB_ES3_compatibility;
        GL_ARB_arrays_of_arrays = caps.GL_ARB_arrays_of_arrays;
        GL_ARB_base_instance = caps.GL_ARB_base_instance;
        GL_ARB_bindless_texture = caps.GL_ARB_bindless_texture;
        GL_ARB_blend_func_extended = caps.GL_ARB_blend_func_extended;
        GL_ARB_buffer_storage = caps.GL_ARB_buffer_storage;
        GL_ARB_cl_event = caps.GL_ARB_cl_event;
        GL_ARB_clear_buffer_object = caps.GL_ARB_clear_buffer_object;
        GL_ARB_clear_texture = caps.GL_ARB_clear_texture;
        GL_ARB_clip_control = caps.GL_ARB_clip_control;
        GL_ARB_color_buffer_float = caps.GL_ARB_color_buffer_float;
        GL_ARB_compatibility = caps.GL_ARB_compatibility;
        GL_ARB_compressed_texture_pixel_storage = caps.GL_ARB_compressed_texture_pixel_storage;
        GL_ARB_compute_shader = caps.GL_ARB_compute_shader;
        GL_ARB_compute_variable_group_size = caps.GL_ARB_compute_variable_group_size;
        GL_ARB_conditional_render_inverted = caps.GL_ARB_conditional_render_inverted;
        GL_ARB_conservative_depth = caps.GL_ARB_conservative_depth;
        GL_ARB_copy_buffer = caps.GL_ARB_copy_buffer;
        GL_ARB_copy_image = caps.GL_ARB_copy_image;
        GL_ARB_cull_distance = caps.GL_ARB_cull_distance;
        GL_ARB_debug_output = caps.GL_ARB_debug_output;
        GL_ARB_depth_buffer_float = caps.GL_ARB_depth_buffer_float;
        GL_ARB_depth_clamp = caps.GL_ARB_depth_clamp;
        GL_ARB_depth_texture = caps.GL_ARB_depth_texture;
        GL_ARB_derivative_control = caps.GL_ARB_derivative_control;
        GL_ARB_direct_state_access = caps.GL_ARB_direct_state_access;
        GL_ARB_draw_buffers = caps.GL_ARB_draw_buffers;
        GL_ARB_draw_buffers_blend = caps.GL_ARB_draw_buffers_blend;
        GL_ARB_draw_elements_base_vertex = caps.GL_ARB_draw_elements_base_vertex;
        GL_ARB_draw_indirect = caps.GL_ARB_draw_indirect;
        GL_ARB_draw_instanced = caps.GL_ARB_draw_instanced;
        GL_ARB_enhanced_layouts = caps.GL_ARB_enhanced_layouts;
        GL_ARB_explicit_attrib_location = caps.GL_ARB_explicit_attrib_location;
        GL_ARB_explicit_uniform_location = caps.GL_ARB_explicit_uniform_location;
        GL_ARB_fragment_coord_conventions = caps.GL_ARB_fragment_coord_conventions;
        GL_ARB_fragment_layer_viewport = caps.GL_ARB_fragment_layer_viewport;
        GL_ARB_fragment_program = caps.GL_ARB_fragment_program;
        GL_ARB_fragment_program_shadow = caps.GL_ARB_fragment_program_shadow;
        GL_ARB_fragment_shader = caps.GL_ARB_fragment_shader;
        GL_ARB_framebuffer_no_attachments = caps.GL_ARB_framebuffer_no_attachments;
        GL_ARB_framebuffer_object = caps.GL_ARB_framebuffer_object;
        GL_ARB_framebuffer_sRGB = caps.GL_ARB_framebuffer_sRGB;
        GL_ARB_geometry_shader4 = caps.GL_ARB_geometry_shader4;
        GL_ARB_get_program_binary = caps.GL_ARB_get_program_binary;
        GL_ARB_get_texture_sub_image = caps.GL_ARB_get_texture_sub_image;
        GL_ARB_gpu_shader5 = caps.GL_ARB_gpu_shader5;
        GL_ARB_gpu_shader_fp64 = caps.GL_ARB_gpu_shader_fp64;
        GL_ARB_half_float_pixel = caps.GL_ARB_half_float_pixel;
        GL_ARB_half_float_vertex = caps.GL_ARB_half_float_vertex;
        GL_ARB_imaging = caps.GL_ARB_imaging;
        GL_ARB_indirect_parameters = caps.GL_ARB_indirect_parameters;
        GL_ARB_instanced_arrays = caps.GL_ARB_instanced_arrays;
        GL_ARB_internalformat_query = caps.GL_ARB_internalformat_query;
        GL_ARB_internalformat_query2 = caps.GL_ARB_internalformat_query2;
        GL_ARB_invalidate_subdata = caps.GL_ARB_invalidate_subdata;
        GL_ARB_map_buffer_alignment = caps.GL_ARB_map_buffer_alignment;
        GL_ARB_map_buffer_range = caps.GL_ARB_map_buffer_range;
        GL_ARB_matrix_palette = caps.GL_ARB_matrix_palette;
        GL_ARB_multi_bind = caps.GL_ARB_multi_bind;
        GL_ARB_multi_draw_indirect = caps.GL_ARB_multi_draw_indirect;
        GL_ARB_multisample = caps.GL_ARB_multisample;
        GL_ARB_multitexture = caps.GL_ARB_multitexture;
        GL_ARB_occlusion_query = caps.GL_ARB_occlusion_query;
        GL_ARB_occlusion_query2 = caps.GL_ARB_occlusion_query2;
        GL_ARB_pipeline_statistics_query = caps.GL_ARB_pipeline_statistics_query;
        GL_ARB_pixel_buffer_object = caps.GL_ARB_pixel_buffer_object;
        GL_ARB_point_parameters = caps.GL_ARB_point_parameters;
        GL_ARB_point_sprite = caps.GL_ARB_point_sprite;
        GL_ARB_program_interface_query = caps.GL_ARB_program_interface_query;
        GL_ARB_provoking_vertex = caps.GL_ARB_provoking_vertex;
        GL_ARB_query_buffer_object = caps.GL_ARB_query_buffer_object;
        GL_ARB_robust_buffer_access_behavior = caps.GL_ARB_robust_buffer_access_behavior;
        GL_ARB_robustness = caps.GL_ARB_robustness;
        GL_ARB_robustness_isolation = false;
        GL_ARB_sample_shading = caps.GL_ARB_sample_shading;
        GL_ARB_sampler_objects = caps.GL_ARB_sampler_objects;
        GL_ARB_seamless_cube_map = caps.GL_ARB_seamless_cube_map;
        GL_ARB_seamless_cubemap_per_texture = caps.GL_ARB_seamless_cubemap_per_texture;
        GL_ARB_separate_shader_objects = caps.GL_ARB_separate_shader_objects;
        GL_ARB_shader_atomic_counters = caps.GL_ARB_shader_atomic_counters;
        GL_ARB_shader_bit_encoding = caps.GL_ARB_shader_bit_encoding;
        GL_ARB_shader_draw_parameters = caps.GL_ARB_shader_draw_parameters;
        GL_ARB_shader_group_vote = caps.GL_ARB_shader_group_vote;
        GL_ARB_shader_image_load_store = caps.GL_ARB_shader_image_load_store;
        GL_ARB_shader_image_size = caps.GL_ARB_shader_image_size;
        GL_ARB_shader_objects = caps.GL_ARB_shader_objects;
        GL_ARB_shader_precision = caps.GL_ARB_shader_precision;
        GL_ARB_shader_stencil_export = caps.GL_ARB_shader_stencil_export;
        GL_ARB_shader_storage_buffer_object = caps.GL_ARB_shader_storage_buffer_object;
        GL_ARB_shader_subroutine = caps.GL_ARB_shader_subroutine;
        GL_ARB_shader_texture_image_samples = caps.GL_ARB_shader_texture_image_samples;
        GL_ARB_shader_texture_lod = caps.GL_ARB_shader_texture_lod;
        GL_ARB_shading_language_100 = caps.GL_ARB_shading_language_100;
        GL_ARB_shading_language_420pack = caps.GL_ARB_shading_language_420pack;
        GL_ARB_shading_language_include = caps.GL_ARB_shading_language_include;
        GL_ARB_shading_language_packing = caps.GL_ARB_shading_language_packing;
        GL_ARB_shadow = caps.GL_ARB_shadow;
        GL_ARB_shadow_ambient = caps.GL_ARB_shadow_ambient;
        GL_ARB_sparse_buffer = caps.GL_ARB_sparse_buffer;
        GL_ARB_sparse_texture = caps.GL_ARB_sparse_texture;
        GL_ARB_stencil_texturing = caps.GL_ARB_stencil_texturing;
        GL_ARB_sync = caps.GL_ARB_sync;
        GL_ARB_tessellation_shader = caps.GL_ARB_tessellation_shader;
        GL_ARB_texture_barrier = caps.GL_ARB_texture_barrier;
        GL_ARB_texture_border_clamp = caps.GL_ARB_texture_border_clamp;
        GL_ARB_texture_buffer_object = caps.GL_ARB_texture_buffer_object;
        GL_ARB_texture_buffer_object_rgb32 = caps.GL_ARB_texture_buffer_object_rgb32;
        GL_ARB_texture_buffer_range = caps.GL_ARB_texture_buffer_range;
        GL_ARB_texture_compression = caps.GL_ARB_texture_compression;
        GL_ARB_texture_compression_bptc = caps.GL_ARB_texture_compression_bptc;
        GL_ARB_texture_compression_rgtc = caps.GL_ARB_texture_compression_rgtc;
        GL_ARB_texture_cube_map = caps.GL_ARB_texture_cube_map;
        GL_ARB_texture_cube_map_array = caps.GL_ARB_texture_cube_map_array;
        GL_ARB_texture_env_add = caps.GL_ARB_texture_env_add;
        GL_ARB_texture_env_combine = caps.GL_ARB_texture_env_combine;
        GL_ARB_texture_env_crossbar = caps.GL_ARB_texture_env_crossbar;
        GL_ARB_texture_env_dot3 = caps.GL_ARB_texture_env_dot3;
        GL_ARB_texture_float = caps.GL_ARB_texture_float;
        GL_ARB_texture_gather = caps.GL_ARB_texture_gather;
        GL_ARB_texture_mirror_clamp_to_edge = caps.GL_ARB_texture_mirror_clamp_to_edge;
        GL_ARB_texture_mirrored_repeat = caps.GL_ARB_texture_mirrored_repeat;
        GL_ARB_texture_multisample = caps.GL_ARB_texture_multisample;
        GL_ARB_texture_non_power_of_two = caps.GL_ARB_texture_non_power_of_two;
        GL_ARB_texture_query_levels = caps.GL_ARB_texture_query_levels;
        GL_ARB_texture_query_lod = caps.GL_ARB_texture_query_lod;
        GL_ARB_texture_rectangle = caps.GL_ARB_texture_rectangle;
        GL_ARB_texture_rg = caps.GL_ARB_texture_rg;
        GL_ARB_texture_rgb10_a2ui = caps.GL_ARB_texture_rgb10_a2ui;
        GL_ARB_texture_stencil8 = caps.GL_ARB_texture_stencil8;
        GL_ARB_texture_storage = caps.GL_ARB_texture_storage;
        GL_ARB_texture_storage_multisample = caps.GL_ARB_texture_storage_multisample;
        GL_ARB_texture_swizzle = caps.GL_ARB_texture_swizzle;
        GL_ARB_texture_view = caps.GL_ARB_texture_view;
        GL_ARB_timer_query = caps.GL_ARB_timer_query;
        GL_ARB_transform_feedback2 = caps.GL_ARB_transform_feedback2;
        GL_ARB_transform_feedback3 = caps.GL_ARB_transform_feedback3;
        GL_ARB_transform_feedback_instanced = caps.GL_ARB_transform_feedback_instanced;
        GL_ARB_transform_feedback_overflow_query = caps.GL_ARB_transform_feedback_overflow_query;
        GL_ARB_transpose_matrix = caps.GL_ARB_transpose_matrix;
        GL_ARB_uniform_buffer_object = caps.GL_ARB_uniform_buffer_object;
        GL_ARB_vertex_array_bgra = caps.GL_ARB_vertex_array_bgra;
        GL_ARB_vertex_array_object = caps.GL_ARB_vertex_array_object;
        GL_ARB_vertex_attrib_64bit = caps.GL_ARB_vertex_attrib_64bit;
        GL_ARB_vertex_attrib_binding = caps.GL_ARB_vertex_attrib_binding;
        GL_ARB_vertex_blend = caps.GL_ARB_vertex_blend;
        GL_ARB_vertex_buffer_object = caps.GL_ARB_vertex_buffer_object;
        GL_ARB_vertex_program = caps.GL_ARB_vertex_program;
        GL_ARB_vertex_shader = caps.GL_ARB_vertex_shader;
        GL_ARB_vertex_type_10f_11f_11f_rev = caps.GL_ARB_vertex_type_10f_11f_11f_rev;
        GL_ARB_vertex_type_2_10_10_10_rev = caps.GL_ARB_vertex_type_2_10_10_10_rev;
        GL_ARB_viewport_array = caps.GL_ARB_viewport_array;
        GL_ARB_window_pos = caps.GL_ARB_window_pos;
        GL_ATI_draw_buffers = false;
        GL_ATI_element_array = false;
        GL_ATI_envmap_bumpmap = false;
        GL_ATI_fragment_shader = false;
        GL_ATI_map_object_buffer = false;
        GL_ATI_meminfo = caps.GL_ATI_meminfo;
        GL_ATI_pn_triangles = false;
        GL_ATI_separate_stencil = false;
        GL_ATI_shader_texture_lod = caps.GL_ATI_shader_texture_lod;
        GL_ATI_text_fragment_shader = false;
        GL_ATI_texture_compression_3dc = caps.GL_ATI_texture_compression_3dc;
        GL_ATI_texture_env_combine3 = false;
        GL_ATI_texture_float = false;
        GL_ATI_texture_mirror_once = false;
        GL_ATI_vertex_array_object = false;
        GL_ATI_vertex_attrib_array_object = false;
        GL_ATI_vertex_streams = false;
        GL_EXT_Cg_shader = false;
        GL_EXT_abgr = caps.GL_EXT_abgr;
        GL_EXT_bgra = caps.GL_EXT_bgra;
        GL_EXT_bindable_uniform = caps.GL_EXT_bindable_uniform;
        GL_EXT_blend_color = caps.GL_EXT_blend_color;
        GL_EXT_blend_equation_separate = caps.GL_EXT_blend_equation_separate;
        GL_EXT_blend_func_separate = caps.GL_EXT_blend_func_separate;
        GL_EXT_blend_minmax = caps.GL_EXT_blend_minmax;
        GL_EXT_blend_subtract = caps.GL_EXT_blend_subtract;
        GL_EXT_compiled_vertex_array = caps.GL_EXT_compiled_vertex_array;
        GL_EXT_depth_bounds_test = caps.GL_EXT_depth_bounds_test;
        GL_EXT_direct_state_access = caps.GL_EXT_direct_state_access;
        GL_EXT_draw_buffers2 = caps.GL_EXT_draw_buffers2;
        GL_EXT_draw_instanced = caps.GL_EXT_draw_instanced;
        GL_EXT_draw_range_elements = false;
        GL_EXT_fog_coord = false;
        GL_EXT_framebuffer_blit = caps.GL_EXT_framebuffer_blit;
        GL_EXT_framebuffer_multisample = caps.GL_EXT_framebuffer_multisample;
        GL_EXT_framebuffer_multisample_blit_scaled = caps.GL_EXT_framebuffer_multisample_blit_scaled;
        GL_EXT_framebuffer_object = caps.GL_EXT_framebuffer_object;
        GL_EXT_framebuffer_sRGB = caps.GL_EXT_framebuffer_sRGB;
        GL_EXT_geometry_shader4 = caps.GL_EXT_geometry_shader4;
        GL_EXT_gpu_program_parameters = caps.GL_EXT_gpu_program_parameters;
        GL_EXT_gpu_shader4 = caps.GL_EXT_gpu_shader4;
        GL_EXT_multi_draw_arrays = false;
        GL_EXT_packed_depth_stencil = caps.GL_EXT_packed_depth_stencil;
        GL_EXT_packed_float = caps.GL_EXT_packed_float;
        GL_EXT_packed_pixels = false;
        GL_EXT_paletted_texture = false;
        GL_EXT_pixel_buffer_object = caps.GL_EXT_pixel_buffer_object;
        GL_EXT_point_parameters = caps.GL_EXT_point_parameters;
        GL_EXT_provoking_vertex = caps.GL_EXT_provoking_vertex;
        GL_EXT_rescale_normal = false;
        GL_EXT_secondary_color = caps.GL_EXT_secondary_color;
        GL_EXT_separate_shader_objects = caps.GL_EXT_separate_shader_objects;
        GL_EXT_separate_specular_color = false;
        GL_EXT_shader_image_load_store = caps.GL_EXT_shader_image_load_store;
        GL_EXT_shadow_funcs = caps.GL_EXT_shadow_funcs;
        GL_EXT_shared_texture_palette = caps.GL_EXT_shared_texture_palette;
        GL_EXT_stencil_clear_tag = caps.GL_EXT_stencil_clear_tag;
        GL_EXT_stencil_two_side = caps.GL_EXT_stencil_two_side;
        GL_EXT_stencil_wrap = caps.GL_EXT_stencil_wrap;
        GL_EXT_texture_3d = false;
        GL_EXT_texture_array = caps.GL_EXT_texture_array;
        GL_EXT_texture_buffer_object = caps.GL_EXT_texture_buffer_object;
        GL_EXT_texture_compression_latc = caps.GL_EXT_texture_compression_latc;
        GL_EXT_texture_compression_rgtc = caps.GL_EXT_texture_compression_rgtc;
        GL_EXT_texture_compression_s3tc = caps.GL_EXT_texture_compression_s3tc;
        GL_EXT_texture_env_combine = false;
        GL_EXT_texture_env_dot3 = false;
        GL_EXT_texture_filter_anisotropic = caps.GL_EXT_texture_filter_anisotropic;
        GL_EXT_texture_integer = caps.GL_EXT_texture_integer;
        GL_EXT_texture_lod_bias = false;
        GL_EXT_texture_mirror_clamp = caps.GL_EXT_texture_mirror_clamp;
        GL_EXT_texture_rectangle = false;
        GL_EXT_texture_sRGB = caps.GL_EXT_texture_sRGB;
        GL_EXT_texture_sRGB_decode = caps.GL_EXT_texture_sRGB_decode;
        GL_EXT_texture_shared_exponent = caps.GL_EXT_texture_shared_exponent;
        GL_EXT_texture_snorm = caps.GL_EXT_texture_snorm;
        GL_EXT_texture_swizzle = caps.GL_EXT_texture_swizzle;
        GL_EXT_timer_query = caps.GL_EXT_timer_query;
        GL_EXT_transform_feedback = caps.GL_EXT_transform_feedback;
        GL_EXT_vertex_array_bgra = caps.GL_EXT_vertex_array_bgra;
        GL_EXT_vertex_attrib_64bit = caps.GL_EXT_vertex_attrib_64bit;
        GL_EXT_vertex_shader = false;
        GL_EXT_vertex_weighting = false;
        OpenGL11 = caps.OpenGL11;
        OpenGL12 = caps.OpenGL12;
        OpenGL13 = caps.OpenGL13;
        OpenGL14 = caps.OpenGL14;
        OpenGL15 = caps.OpenGL15;
        OpenGL20 = caps.OpenGL20;
        OpenGL21 = caps.OpenGL21;
        OpenGL30 = caps.OpenGL30;
        OpenGL31 = caps.OpenGL31;
        OpenGL32 = caps.OpenGL32;
        OpenGL33 = caps.OpenGL33;
        OpenGL40 = caps.OpenGL40;
        OpenGL41 = caps.OpenGL41;
        OpenGL42 = caps.OpenGL42;
        OpenGL43 = caps.OpenGL43;
        OpenGL44 = caps.OpenGL44;
        OpenGL45 = caps.OpenGL45;
        GL_GREMEDY_frame_terminator = caps.GL_GREMEDY_frame_terminator;
        GL_GREMEDY_string_marker = caps.GL_GREMEDY_string_marker;
        GL_HP_occlusion_test = false;
        GL_IBM_rasterpos_clip = false;
        GL_INTEL_map_texture = caps.GL_INTEL_map_texture;
        GL_KHR_context_flush_control = caps.GL_KHR_context_flush_control;
        GL_KHR_debug = caps.GL_KHR_debug;
        GL_KHR_robust_buffer_access_behavior = caps.GL_KHR_robust_buffer_access_behavior;
        GL_KHR_robustness = caps.GL_KHR_robustness;
        GL_KHR_texture_compression_astc_ldr = caps.GL_KHR_texture_compression_astc_ldr;
        GL_NVX_gpu_memory_info = caps.GL_NVX_gpu_memory_info;
        GL_NV_bindless_multi_draw_indirect = caps.GL_NV_bindless_multi_draw_indirect;
        GL_NV_bindless_texture = caps.GL_NV_bindless_texture;
        GL_NV_blend_equation_advanced = caps.GL_NV_blend_equation_advanced;
        GL_NV_blend_square = caps.GL_NV_blend_square;
        GL_NV_compute_program5 = false;
        GL_NV_conditional_render = caps.GL_NV_conditional_render;
        GL_NV_copy_depth_to_color = caps.GL_NV_copy_depth_to_color;
        GL_NV_copy_image = caps.GL_NV_copy_image;
        GL_NV_deep_texture3D = caps.GL_NV_deep_texture3D;
        GL_NV_depth_buffer_float = caps.GL_NV_depth_buffer_float;
        GL_NV_depth_clamp = caps.GL_NV_depth_clamp;
        GL_NV_draw_texture = caps.GL_NV_draw_texture;
        GL_NV_evaluators = false;
        GL_NV_explicit_multisample = caps.GL_NV_explicit_multisample;
        GL_NV_fence = caps.GL_NV_fence;
        GL_NV_float_buffer = caps.GL_NV_float_buffer;
        GL_NV_fog_distance = caps.GL_NV_fog_distance;
        GL_NV_fragment_program = false;
        GL_NV_fragment_program2 = false;
        GL_NV_fragment_program4 = caps.GL_NV_fragment_program4;
        GL_NV_fragment_program_option = caps.GL_NV_fragment_program_option;
        GL_NV_framebuffer_multisample_coverage = caps.GL_NV_framebuffer_multisample_coverage;
        GL_NV_geometry_program4 = false;
        GL_NV_geometry_shader4 = caps.GL_NV_geometry_shader4;
        GL_NV_gpu_program4 = false;
        GL_NV_gpu_program5 = false;
        GL_NV_gpu_program5_mem_extended = false;
        GL_NV_gpu_shader5 = caps.GL_NV_gpu_shader5;
        GL_NV_half_float = caps.GL_NV_half_float;
        GL_NV_light_max_exponent = caps.GL_NV_light_max_exponent;
        GL_NV_multisample_coverage = caps.GL_NV_multisample_coverage;
        GL_NV_multisample_filter_hint = caps.GL_NV_multisample_filter_hint;
        GL_NV_occlusion_query = false;
        GL_NV_packed_depth_stencil = caps.GL_NV_packed_depth_stencil;
        GL_NV_parameter_buffer_object = false;
        GL_NV_parameter_buffer_object2 = false;
        GL_NV_path_rendering = caps.GL_NV_path_rendering;
        GL_NV_pixel_data_range = caps.GL_NV_pixel_data_range;
        GL_NV_point_sprite = caps.GL_NV_point_sprite;
        GL_NV_present_video = false;
        GL_NV_primitive_restart = caps.GL_NV_primitive_restart;
        GL_NV_register_combiners = false;
        GL_NV_register_combiners2 = false;
        GL_NV_shader_atomic_counters = false;
        GL_NV_shader_atomic_float = caps.GL_NV_shader_atomic_float;
        GL_NV_shader_buffer_load = caps.GL_NV_shader_buffer_load;
        GL_NV_shader_buffer_store = caps.GL_NV_shader_buffer_store;
        GL_NV_shader_storage_buffer_object = false;
        GL_NV_tessellation_program5 = false;
        GL_NV_texgen_reflection = caps.GL_NV_texgen_reflection;
        GL_NV_texture_barrier = caps.GL_NV_texture_barrier;
        GL_NV_texture_compression_vtc = caps.GL_NV_texture_compression_vtc;
        GL_NV_texture_env_combine4 = false;
        GL_NV_texture_expand_normal = false;
        GL_NV_texture_multisample = caps.GL_NV_texture_multisample;
        GL_NV_texture_rectangle = false;
        GL_NV_texture_shader = caps.GL_NV_texture_shader;
        GL_NV_texture_shader2 = caps.GL_NV_texture_shader2;
        GL_NV_texture_shader3 = caps.GL_NV_texture_shader3;
        GL_NV_transform_feedback = caps.GL_NV_transform_feedback;
        GL_NV_transform_feedback2 = caps.GL_NV_transform_feedback2;
        GL_NV_vertex_array_range = caps.GL_NV_vertex_array_range;
        GL_NV_vertex_array_range2 = caps.GL_NV_vertex_array_range2;
        GL_NV_vertex_attrib_integer_64bit = caps.GL_NV_vertex_attrib_integer_64bit;
        GL_NV_vertex_buffer_unified_memory = caps.GL_NV_vertex_buffer_unified_memory;
        GL_NV_vertex_program = false;
        GL_NV_vertex_program1_1 = false;
        GL_NV_vertex_program2 = false;
        GL_NV_vertex_program2_option = false;
        GL_NV_vertex_program3 = false;
        GL_NV_vertex_program4 = false;
        GL_NV_video_capture = false;
        GL_SGIS_generate_mipmap = false;
        GL_SGIS_texture_lod = false;
        GL_SUN_slice_accum = false;
    }
}
